### PR TITLE
A thing that I learned later on

### PR DESCRIPTION
**Pull request by Paradox304**

### CODE REVIEW

**Comment by hiilikewiki** [comment]
If I remember correctly this is already done by OpenMod

**Comment by Trojaner** [comment]
OpenMod will automatically throw a UserFriendlyException when you try to access a paramter that is not inputted

**Comment by Paradox304** [comment]
It doesn't actually, you have to write this piece of code for it to do it. Otherwise it throws the exception to the console.

**Comment by Trojaner** [comment]
The exception needs to be fixed in that case

**Pull request closed without merging**
