### PR TITLE
Add services and fix my earlier mistakes

### PR DESCRIPTION
**Pull request by hiilikewiki**
Add simple di explanation, with an example. TODO: Add list of services (though maybe should leave it out because it's pretty obvious)

### CODE REVIEW

**Comment by Johnanater** [comment]
It might be better to call it "EchoCommand"

**Comment by Trojaner** [comment]
Conflicts need to be resolved

**Comment by hiilikewiki** [comment]
Lemme fix naming

**Comment by hiilikewiki** [comment]
Ok done @Trojaner

**Pull request merged**
