### PR TITLE
Add setting up workspace and recommendations for required software

### PR DESCRIPTION
**Pull request by hiilikewiki**

### CODE REVIEW

**Comment by Trojaner** [comment]
Sadly I already began writing docs for creating plugins

**Comment by hiilikewiki** [comment]
Lol ok

**Comment by Trojaner** [comment]
Feel free to edit and contribute to: https://github.com/openmod/openmod-docs/blob/master/content/development-guide/making-your-first-plugin.md (e.g. by adding a Ryder installation guide)

(templates are still being published to NuGet so it may not work yet)

**Comment by hiilikewiki** [comment]
Alright will do

**Pull request closed without merging**
