### PR TITLE
Removed unnecessary gender link in the documentation.

### PR DESCRIPTION
**Pull request by Charterino**
Changed 'he' to 'they' as it is an unnecessary gender link.

### CODE REVIEW

**Comment by rube200** [comment]
`Permissions allow defining which actions useras are permitted to execute and which they are not`?
1 more thing
ARE U ASSUMING MY GENDER?

**Comment by archie426** [comment]
@rube200 yeah you’re a girl lets sex

**Comment by rube200** [comment]
AM I? *sex noises*

**Comment by Charterino** [comment]
yes very much so

вс, 16 авг. 2020 г., 19:48 Rúben Garcia <notifications@github.com>:

**Pull request merged**
